-- ==============================================================================
-- SCRIPT DE SEGURANÇA E POLÍTICAS DE ROW LEVEL SECURITY (RLS) PARA O SUPABASE
-- Execute este script no SQL Editor do painel Supabase (https://supabase.com/dashboard)
-- Versão endurecida: sem SELECT/INSERT anon direto, RBAC via app_metadata,
-- RPCs validadas com SECURITY DEFINER + search_path fixo.
-- ==============================================================================

-- 0. CRIAÇÃO DAS TABELAS SE NÃO EXISTIREM
CREATE TABLE IF NOT EXISTS pedidos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente TEXT NOT NULL CHECK (char_length(cliente) BETWEEN 2 AND 120),
  telefone TEXT CHECK (telefone IS NULL OR char_length(telefone) <= 30),
  servico TEXT NOT NULL CHECK (char_length(servico) BETWEEN 2 AND 200),
  setor TEXT DEFAULT 'Geral' CHECK (char_length(setor) <= 60),
  status TEXT DEFAULT 'Pendente' CHECK (status IN ('Pendente','Agendado','Em andamento','Em produção','Concluído','Cancelado')),
  valor NUMERIC DEFAULT 0 CHECK (valor >= 0 AND valor <= 1000000),
  data_pedido TEXT CHECK (data_pedido IS NULL OR char_length(data_pedido) <= 60),
  observacoes TEXT CHECK (observacoes IS NULL OR char_length(observacoes) <= 4000),
  avaliacao_csat INT CHECK (avaliacao_csat IS NULL OR (avaliacao_csat BETWEEN 1 AND 5)),
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_pedidos_user_id ON pedidos(user_id);
CREATE INDEX IF NOT EXISTS idx_pedidos_created_at ON pedidos(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_pedidos_telefone ON pedidos(telefone);

CREATE TABLE IF NOT EXISTS configuracoes_chatbot (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chave TEXT UNIQUE NOT NULL,
  valor JSONB,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar RLS nas tabelas
ALTER TABLE pedidos ENABLE ROW LEVEL SECURITY;
ALTER TABLE configuracoes_chatbot ENABLE ROW LEVEL SECURITY;
ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- IMPORTANTE SOBRE CARGOS (ROLES):
-- NÃO use auth.jwt() -> 'user_metadata' ->> 'role' (o usuário edita isso).
-- Defina o cargo em app_metadata via Dashboard > Auth > Users > Edit > App Metadata:
--   { "role": "admin" }
-- ou via Admin API. As políticas abaixo usam app_metadata.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- configuracoes_chatbot: NENHUM acesso anon. Leitura pública só da chave
-- 'public_config' (sem segredos). Segredos (groq key etc.) NUNCA aqui.
-- ----------------------------------------------------------------------------
DROP POLICY IF EXISTS "cfg_chatbot_public_select" ON configuracoes_chatbot;
DROP POLICY IF EXISTS "cfg_chatbot_admin_all" ON configuracoes_chatbot;
DROP POLICY IF EXISTS "cfg_chatbot_public_config_select" ON configuracoes_chatbot;

-- Apenas a chave public_config pode ser lida por anon/authenticated.
-- Garanta que valor de public_config contenha SÓ: nomeEmpresa, setores, tabelaPrecos.
CREATE POLICY "cfg_chatbot_public_config_select" ON configuracoes_chatbot
FOR SELECT TO anon, authenticated
USING (chave = 'public_config');

CREATE POLICY "cfg_chatbot_admin_all" ON configuracoes_chatbot
FOR ALL TO authenticated
USING (((auth.jwt() -> 'app_metadata' ->> 'role') IN ('admin', 'administrador')))
WITH CHECK (((auth.jwt() -> 'app_metadata' ->> 'role') IN ('admin', 'administrador')));

-- ----------------------------------------------------------------------------
-- pedidos: políticas para authenticated (dono + admin via app_metadata)
-- ----------------------------------------------------------------------------
DROP POLICY IF EXISTS "pedidos_select_policy" ON pedidos;
DROP POLICY IF EXISTS "pedidos_insert_policy" ON pedidos;
DROP POLICY IF EXISTS "pedidos_update_policy" ON pedidos;
DROP POLICY IF EXISTS "pedidos_delete_policy" ON pedidos;
DROP POLICY IF EXISTS "pedidos_chatbot_anon_insert_policy" ON pedidos;
DROP POLICY IF EXISTS "pedidos_chatbot_anon_select_policy" ON pedidos;

-- SELECT: dono vê o seu; admin (app_metadata) vê tudo.
CREATE POLICY "pedidos_select_policy" ON pedidos
FOR SELECT TO authenticated
USING (
  (auth.uid() = user_id)
  OR ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('admin', 'administrador'))
);

-- INSERT autenticado: user_id deve ser o próprio, exceto admin.
-- Impede linhas de sistema via API (setor __* reservado ao service_role).
CREATE POLICY "pedidos_insert_policy" ON pedidos
FOR INSERT TO authenticated
WITH CHECK (
  (
    (auth.uid() = user_id)
    OR ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('admin', 'administrador'))
  )
  AND (setor NOT LIKE '\_\_%' ESCAPE '\')
  AND (cliente IS NOT NULL AND char_length(cliente) BETWEEN 2 AND 120)
  AND (servico IS NOT NULL AND char_length(servico) BETWEEN 2 AND 200)
  AND (valor IS NULL OR (valor >= 0 AND valor <= 1000000))
  AND (observacoes IS NULL OR char_length(observacoes) <= 4000)
);

-- UPDATE: dono ou admin podem ver a linha; nova versão validada via WITH CHECK.
-- Impede sequestro de linha (troca de user_id) por não-admin.
CREATE POLICY "pedidos_update_policy" ON pedidos
FOR UPDATE TO authenticated
USING (
  (auth.uid() = user_id)
  OR ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('admin', 'administrador'))
)
WITH CHECK (
  (
    (auth.uid() = user_id)
    OR ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('admin', 'administrador'))
  )
  AND (setor NOT LIKE '\_\_%' ESCAPE '\')
  AND (valor IS NULL OR (valor >= 0 AND valor <= 1000000))
  AND (observacoes IS NULL OR char_length(observacoes) <= 4000)
);

-- DELETE: dono pode deletar apenas os seus próprios pedidos; admin (app_metadata) pode deletar tudo.
-- Garante isolamento estrito: nenhum usuário pode deletar pedidos de outro.
CREATE POLICY "pedidos_delete_policy" ON pedidos
FOR DELETE TO authenticated
USING (
  (auth.uid() = user_id)
  OR ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('admin', 'administrador'))
);


-- NENHUMA policy anon direta em pedidos (sem SELECT/INSERT/UPDATE/DELETE anon).
-- Chatbot público usa SOMENTE as RPCs abaixo (SECURITY DEFINER).

-- ----------------------------------------------------------------------------
-- RPC: criar_pedido_publico — único caminho de escrita anônima.
-- Valida tudo no servidor, limita tamanho e impede user_id/setor reservado.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION criar_pedido_publico(
  p_cliente TEXT,
  p_telefone TEXT DEFAULT NULL,
  p_servico TEXT DEFAULT 'Solicitação via Chatbot',
  p_setor TEXT DEFAULT 'Geral',
  p_valor NUMERIC DEFAULT 0,
  p_data_pedido TEXT DEFAULT NULL,
  p_observacoes TEXT DEFAULT NULL
)
RETURNS TABLE (id BIGINT, status TEXT)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_cliente TEXT := NULLIF(BTRIM(p_cliente), '');
  v_telefone TEXT := NULLIF(BTRIM(SUBSTRING(p_telefone FROM 1 FOR 30)), '');
  v_servico TEXT := NULLIF(BTRIM(p_servico), 'Solicitação via Chatbot');
  v_setor TEXT := COALESCE(NULLIF(BTRIM(p_setor), ''), 'Geral');
  v_valor NUMERIC := COALESCE(p_valor, 0);
  v_data TEXT := NULLIF(BTRIM(SUBSTRING(p_data_pedido FROM 1 FOR 60)), '');
  v_obs TEXT := NULLIF(BTRIM(SUBSTRING(p_observacoes FROM 1 FOR 4000)), '');
  v_id BIGINT;
BEGIN
  -- Validações mínimas (anti-spam/poisoning)
  IF v_cliente IS NULL OR char_length(v_cliente) < 2 OR char_length(v_cliente) > 120 THEN
    RAISE EXCEPTION 'Nome do cliente inválido (2-120 caracteres).';
  END IF;
  IF v_servico IS NULL OR char_length(v_servico) < 2 OR char_length(v_servico) > 200 THEN
    RAISE EXCEPTION 'Serviço inválido (2-200 caracteres).';
  END IF;
  IF v_telefone IS NOT NULL AND char_length(REGEXP_REPLACE(v_telefone, '\D', '', 'g')) < 8 THEN
    RAISE EXCEPTION 'Telefone inválido.';
  END IF;
  IF v_valor IS NULL OR v_valor < 0 OR v_valor > 1000000 THEN
    RAISE EXCEPTION 'Valor inválido.';
  END IF;
  -- Setores permitidos (allowlist). Ajuste conforme seu negócio.
  IF v_setor NOT IN ('Geral','Oficina','Pet Shop','Informática','Vendas','Manutenção','Design') THEN
    v_setor := 'Geral';
  END IF;

  -- Anti-flood simples: max 5 pedidos com mesmo telefone nos últimos 10 minutos
  IF v_telefone IS NOT NULL THEN
    IF (SELECT COUNT(*) FROM pedidos
        WHERE telefone = v_telefone
          AND created_at > NOW() - INTERVAL '10 minutes') >= 5 THEN
      RAISE EXCEPTION 'Muitos pedidos em sequência. Aguarde alguns minutos.';
    END IF;
  END IF;

  INSERT INTO pedidos (cliente, telefone, servico, setor, valor, data_pedido, observacoes, status, user_id)
  VALUES (v_cliente, COALESCE(v_telefone, 'Não informado'), v_servico, v_setor, v_valor, v_data, v_obs, 'Pendente', NULL)
  RETURNING pedidos.id INTO v_id;

  RETURN QUERY SELECT v_id, 'Pendente'::TEXT;
END;
$$;

-- ----------------------------------------------------------------------------
-- RPC: consultar_pedido_publico — exige ID + telefone completo (2 fatores).
-- Retorna PII mascarada (telefone parcial, sem observações internas longas).
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION consultar_pedido_publico(
  p_id INT DEFAULT NULL,
  p_telefone TEXT DEFAULT NULL
)
RETURNS TABLE (
  id BIGINT,
  cliente TEXT,
  servico TEXT,
  setor TEXT,
  data_pedido TEXT,
  status TEXT,
  valor NUMERIC,
  created_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_tel_digits TEXT := REGEXP_REPLACE(COALESCE(p_telefone, ''), '\D', '', 'g');
BEGIN
  -- Exige AMBOS: id válido + telefone com DDD (>=10 dígitos) para evitar enumeração
  IF p_id IS NULL OR p_id <= 0 THEN
    RAISE EXCEPTION 'Informe o número do pedido.';
  END IF;
  IF char_length(v_tel_digits) < 10 THEN
    RAISE EXCEPTION 'Informe o telefone completo com DDD usado no pedido.';
  END IF;

  RETURN QUERY
  SELECT p.id, p.cliente, p.servico, p.setor, p.data_pedido, p.status, p.valor, p.created_at
  FROM pedidos p
  WHERE p.id = p_id
    AND REGEXP_REPLACE(COALESCE(p.telefone, ''), '\D', '', 'g') LIKE '%' || RIGHT(v_tel_digits, 8) || '%'
  LIMIT 1;
END;
$$;

-- RPC: avaliar_pedido_publico — permite CSAT 1-5 sem UPDATE anon direto.
CREATE OR REPLACE FUNCTION avaliar_pedido_publico(p_id INT, p_nota INT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF p_id IS NULL OR p_id <= 0 THEN RAISE EXCEPTION 'Pedido inválido.'; END IF;
  IF p_nota IS NULL OR p_nota < 1 OR p_nota > 5 THEN RAISE EXCEPTION 'Nota inválida.'; END IF;
  UPDATE pedidos SET avaliacao_csat = p_nota WHERE id = p_id AND avaliacao_csat IS NULL;
END;
$$;

-- Permissões mínimas das RPCs (sem acesso direto à tabela)
REVOKE ALL ON FUNCTION criar_pedido_publico(TEXT, TEXT, TEXT, TEXT, NUMERIC, TEXT, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION criar_pedido_publico(TEXT, TEXT, TEXT, TEXT, NUMERIC, TEXT, TEXT) TO anon, authenticated;
REVOKE ALL ON FUNCTION consultar_pedido_publico(INT, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION consultar_pedido_publico(INT, TEXT) TO anon, authenticated;
REVOKE ALL ON FUNCTION avaliar_pedido_publico(INT, INT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION avaliar_pedido_publico(INT, INT) TO anon, authenticated;

-- ----------------------------------------------------------------------------
-- Limpeza de restos inseguros: remove config com segredo embutido em pedidos
-- (rode uma vez e confira antes em produção).
-- ----------------------------------------------------------------------------
-- DELETE FROM pedidos WHERE setor LIKE '\_\_%' ESCAPE '\';
-- Mova nomeEmpresa/setores/tabelaPrecos para:
--   INSERT INTO configuracoes_chatbot (chave, valor)
--   VALUES ('public_config', '{"nomeEmpresa":"Sua Empresa","setoresDisponiveis":[...]}')
--   ON CONFLICT (chave) DO UPDATE SET valor = EXCLUDED.valor, updated_at = NOW();
-- NUNCA grave groqApiKey / secrets em pedidos nem em configuracoes_chatbot público.

-- ----------------------------------------------------------------------------
-- STORAGE: NÃO crie bucket público com INSERT anon.
-- Se precisar de anexos, use bucket PRIVADO + upload via Edge Function
-- autenticada + antivírus + limite tipo/tamanho. Nenhuma policy anon abaixo.
-- ----------------------------------------------------------------------------

-- ============================================================================
-- PROCEDIMENTO DE TESTE / AVALIAÇÃO ACADÊMICA: PROMOVER USUÁRIO A ADMIN
-- Permite ao avaliador/professor promover qualquer conta criada a Administrador
-- com apenas uma linha no SQL Editor do Supabase:
--   SELECT promover_usuario_admin('professor@exemplo.com');
-- ============================================================================
CREATE OR REPLACE FUNCTION promover_usuario_admin(p_email TEXT)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, pg_temp
AS $$
DECLARE
  v_user_id UUID;
BEGIN
  SELECT id INTO v_user_id FROM auth.users WHERE LOWER(email) = LOWER(TRIM(p_email));
  IF v_user_id IS NULL THEN
    RETURN 'Usuário com o e-mail "' || TRIM(p_email) || '" não foi encontrado no sistema auth.users. Crie a conta antes no painel.';
  END IF;

  UPDATE auth.users
  SET raw_app_meta_data = COALESCE(raw_app_meta_data, '{}'::jsonb) || '{"role": "admin"}'::jsonb
  WHERE id = v_user_id;

  RETURN 'Sucesso: Usuário "' || TRIM(p_email) || '" promovido a Administrador! Faça logout e login no painel para aplicar o novo cargo.';
END;
$$;

